controller_list:
  - name: fake_manipulator_controller
    joints:
      - joint_1_s
      - joint_2_l1
      - joint_3_l2
      - joint_4_u
      - joint_5_r
      - joint_6_b
      - joint_7_t
initial:  # Define initial robot poses.
#  - group: manipulator
#    pose: home
